// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuditTrailClient is the client API for AuditTrail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditTrailClient interface {
	FetchAuditTrail(ctx context.Context, in *FetchAuditTrailRequest, opts ...grpc.CallOption) (*FetchAuditTrailResponse, error)
}

type auditTrailClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditTrailClient(cc grpc.ClientConnInterface) AuditTrailClient {
	return &auditTrailClient{cc}
}

func (c *auditTrailClient) FetchAuditTrail(ctx context.Context, in *FetchAuditTrailRequest, opts ...grpc.CallOption) (*FetchAuditTrailResponse, error) {
	out := new(FetchAuditTrailResponse)
	err := c.cc.Invoke(ctx, "/AuditTrail/FetchAuditTrail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditTrailServer is the server API for AuditTrail service.
// All implementations must embed UnimplementedAuditTrailServer
// for forward compatibility
type AuditTrailServer interface {
	FetchAuditTrail(context.Context, *FetchAuditTrailRequest) (*FetchAuditTrailResponse, error)
	mustEmbedUnimplementedAuditTrailServer()
}

// UnimplementedAuditTrailServer must be embedded to have forward compatible implementations.
type UnimplementedAuditTrailServer struct {
}

func (UnimplementedAuditTrailServer) FetchAuditTrail(context.Context, *FetchAuditTrailRequest) (*FetchAuditTrailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchAuditTrail not implemented")
}
func (UnimplementedAuditTrailServer) mustEmbedUnimplementedAuditTrailServer() {}

// UnsafeAuditTrailServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditTrailServer will
// result in compilation errors.
type UnsafeAuditTrailServer interface {
	mustEmbedUnimplementedAuditTrailServer()
}

func RegisterAuditTrailServer(s grpc.ServiceRegistrar, srv AuditTrailServer) {
	s.RegisterService(&AuditTrail_ServiceDesc, srv)
}

func _AuditTrail_FetchAuditTrail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchAuditTrailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditTrailServer).FetchAuditTrail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuditTrail/FetchAuditTrail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditTrailServer).FetchAuditTrail(ctx, req.(*FetchAuditTrailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditTrail_ServiceDesc is the grpc.ServiceDesc for AuditTrail service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditTrail_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuditTrail",
	HandlerType: (*AuditTrailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchAuditTrail",
			Handler:    _AuditTrail_FetchAuditTrail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
